### ISSUE TITLE
Use semantic line-breaks

### ISSUE THREAD

**Issue by jcsalomon** [rosarior/Code-of-Merit#5]
See <http://rhodesmill.org/brandon/2012/one-sentence-per-line/> for a description of this technique.

Rationale: Since this document will likely undergo significant wording changes as it develops, it will be helpful to format the Markdown code so as to make the Git diffs most easily usable.

**Comment by rosarior** [comment]
Thanks! Started separating the text into smaller lines.

**Comment by rosarior** [comment]
Text is now split closer to the described technique. Patch for improvement welcomed. Thanks for opening this issue.
